name: efyu-lang

version: 0.1.0.0
license:             MIT
license-file:        LICENSE
author:              Akshay Nair
maintainer:          phenax5@gmail.com
build-type:          Simple

ghc-options:
  -Wdefault
  -Wextra
  -Wno-unused-do-bind
  -fwarn-tabs
  -Wname-shadowing

dependencies:
  - base >=4.14 && <4.15
  - containers
  - megaparsec
  - pretty-simple
  - text
  - transformers

default-extensions:
  - LambdaCase
  - QuasiQuotes
  - TupleSections
  - FlexibleInstances
  - TypeSynonymInstances
  - DataKinds
  - KindSignatures

library:
  source-dirs: src/

executables:
  efyu:
    main: Main.hs
    source-dirs:
      - app/
      - src/

tests:
  efyu-test:
    main: _main.hs
    dependencies:
      - hspec
      - hspec-megaparsec
      - raw-strings-qq
      # - hspec-golden
    source-dirs:
      - tests/
      - src/
